FROM public.ecr.aws/lambda/nodejs:14 as build-image

WORKDIR /var/task
ARG FUNCTION_DIR=$WORKDIR

COPY . $WORKDIR

RUN npm install 
RUN npx lerna bootstrap
RUN npm test
RUN npm run build

CMD ["packages/api/lib/lambda/index.handler"]
