FROM public.ecr.aws/lambda/nodejs:14 as build-image

WORKDIR /var/task
ARG FUNCTION_DIR=$WORKDIR

COPY . $WORKDIR

RUN cd /var/task/packages/renderer && npm prune --production
RUN cd /var/task/packages/api && npm rebuild canvas --update-binary && npm prune --production
RUN npx lerna link

FROM public.ecr.aws/lambda/nodejs:14

WORKDIR /var/task
COPY --from=build-image /var/task/packages /var/task/packages

CMD ["packages/api/lib/lambda/index.handler"]
